common/models/Team.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use common\models\TeamMembers;
use frontend\models\TeamInvites;
use frontend\models\UserTemplates;
use frontend\models\UserTemplatesToTeam;
/**
 * This is the model class for table "team".
 *
 * @property integer $id
 * @property string $name
 * @property integer $userId
 * @property string $comments
 * @property integer $created_at
 * @property integer $updated_at
 */
class Team extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'team';
    }
          public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),

            ]
        ];
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'userId'], 'required'],
            [['userId'], 'integer'],
            [['comments'], 'string'],
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Команда'),
            'userId' => Yii::t('app', 'User ID'),
            'comments' => Yii::t('app', 'Комментарии'),
            'created_at' => Yii::t('app', 'Создана'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }
    public function beforeDelete()
{
         TeamInvites::deleteAll(['teamId'=> $this->id]);
        TeamMembers::deleteAll(['teamId'=> $this->id]);
        return parent::beforeDelete();

}
        public function getUser()
    {
          return $this->hasOne(User::className(), ['id' => 'userId']);
    }
     public function getInvites()
{
    return $this->hasMany(TeamInvites::className(), ['teamId' => 'id']);
}
     public function getMembers()
{
    return $this->hasMany(TeamMembers::className(), ['teamId' => 'id']);
}
     public function getMembers_count()
{
    return TeamMembers::find()->where(['teamId' => $this->id])->groupBy('memberId')->count();
}
     public function getTemplates()
	{
	    return $this->hasMany(UserTemplates::className(), ['teamId' => 'id']);
	}
     public function getTemplates_count()
	{
	    return  $this->hasMany(UserTemplates::className(), ['id' => 'templateId'])
    ->viaTable('user_templates_to_team', ['teamId' => 'id'])->count();
	}
}

backend/controllers/TeamController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Team;
use common\models\User;
use common\models\TeamMembers;
use frontend\models\TeamInvites;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TeamController implements the CRUD actions for Team model.
 */
class TeamController extends Controller
{
    public function behaviors()
    {
        return [
         'access' => [
            'class' =>  \yii\filters\AccessControl::className(),
            'rules' => [
                [
                    'allow' => true,
                    'roles' => ['@'],
                ],
            ],
        ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }


    /**
     * Lists all Team models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Team::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Team model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
          $model=$this->findModel($id);
      $members = new TeamInvites();
      $name=Yii::$app->request->post('name');
              if(Yii::$app->request->post('hasEditable')&&!empty($name))
        {
        	$model->name=Yii::$app->request->post('name');
        	$model->save();
        	 $out = Json::encode(['output'=>'', 'message'=>'']);
        	 echo $out;
        	 return;
        }
        if ($members->load(Yii::$app->request->post()) && $members->save()) {
                 $members->teamId=$id;
                 $members->userId=Yii::$app->user->id;
                 $members->invite_code=Yii::$app->security->generateRandomString(20);
                 $members->save();
                 $this->SendInvite($model,$members);
                 return $this->redirect(['view', 'id' => $_GET['id']]);
        }
         $leaderProvider = new ActiveDataProvider([
            'query' => User::find()->joinWith('teams',true,'RIGHT JOIN')->where(['teamId' => $id,'member_status'=>1]),
        ]);
          $managerProvider = new ActiveDataProvider([
             'query' => User::find()->joinWith('teams',true,'RIGHT JOIN')->where(['teamId' => $id,'member_status'=>2]),
        ]);
          $invitesProvider = new ActiveDataProvider([
            'query' => TeamInvites::find()->where(['teamId' => $id,'isParsed'=>0]),
        ]);
        return $this->render('view', [
            'model' => $model,
            'members'=> $members,
            'managerProvider'=>$managerProvider,
            'leaderProvider'=>$leaderProvider,
            'invitesProvider'=>$invitesProvider

        ]);
    }


    /**
     * Creates a new Team model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Team;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Team model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Team model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Team model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Team the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Team::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

      public function actionDeleteInvite($id)
    {
        $model=TeamInvites::findOne($id);

        	$model->delete();

        return $this->redirect(['team/'.$model->teamId]);
    }


}

frontend/controllers/TeamController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Team;
use common\models\User;
use common\models\Logger;
use common\models\TeamMembers;
use frontend\models\TeamInvites;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Json;

/**
 * TeamController implements the CRUD actions for Team model.
 */
class TeamController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
         'access' => [
            'class' =>  \yii\filters\AccessControl::className(),
            'rules' => [
                [
                    'allow' => true,
                    'roles' => ['@'],
                ],
            ],
        ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Team models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Team::find()->joinWith('members',true,'RIGHT JOIN')->where(['memberId' => Yii::$app->user->id]),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Team model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
          $model=$this->findModel($id);
      $members = new TeamInvites();
      $name=Yii::$app->request->post('name');
              if(Yii::$app->request->post('hasEditable')&&$model->userId==Yii::$app->user->id&&!empty($name))
        {
        	$model->name=Yii::$app->request->post('name');
        	$model->save();
        	 $out = Json::encode(['output'=>'', 'message'=>'']);
        	 echo $out;
        	 return;
        }
        if ($members->load(Yii::$app->request->post()) && $members->save()) {
                 $members->teamId=$id;
                 $members->userId=Yii::$app->user->id;
                 $members->invite_code=Yii::$app->security->generateRandomString(20);
                 $members->save();
                 $this->SendInvite($model,$members);
                 return $this->redirect(['view', 'id' => $_GET['id']]);
        }
         $leaderProvider = new ActiveDataProvider([
            'query' => User::find()->joinWith('teams',true,'RIGHT JOIN')->where(['teamId' => $id,'member_status'=>1]),
        ]);
          $managerProvider = new ActiveDataProvider([
             'query' => User::find()->joinWith('teams',true,'RIGHT JOIN')->where(['teamId' => $id,'member_status'=>2]),
        ]);
          $invitesProvider = new ActiveDataProvider([
            'query' => TeamInvites::find()->where(['teamId' => $id,'isParsed'=>0]),
        ]);
        return $this->render('view', [
            'model' => $model,
            'members'=> $members,
            'managerProvider'=>$managerProvider,
            'leaderProvider'=>$leaderProvider,
            'invitesProvider'=>$invitesProvider

        ]);
    }

    /**
     * Creates a new Team model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Team();
        $model->name=$_POST['name'];
        $model->userId=Yii::$app->user->id;

        if ($model->validate() && $model->save()) {
            $members=new TeamMembers();
                $members->memberId=Yii::$app->user->id;
                $members->teamId= $model->id;
        	     $members->member_status=1;
        	     $members->save();

           $members=new TeamMembers();
                $members->memberId=Yii::$app->user->id;
                $members->teamId= $model->id;
        	     $members->member_status=2;
        	      $members->save();
        	       Logger::addLog('team','Создана новая команда # '.$model->id);
       	 return $this->redirect(['view', 'id' => $model->id]);
        }
        else
        {
        	//print_r($model->getErrors());
        }
    }

    /**
     * Updates an existing Team model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Team model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model=$this->findModel($id);
        if($model->userId==Yii::$app->user->id)
        {
        	   Logger::addLog('team','Удалена команда # '.$id);
        	$this->findModel($id)->delete();
        }
        return $this->redirect(['index']);
    }

    /**
     * Finds the Team model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Team the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Team::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }


      public function actionDeleteInvite($id)
    {
        $model=TeamInvites::findOne($id);
        if($model->userId==Yii::$app->user->id)
        {
        	$model->delete();
        }
        return $this->redirect(['team/'.$model->teamId]);
    }
      public function actionDeleteMember()
    {
        $teamId=Yii::$app->request->get('teamId');
        $id=Yii::$app->request->get('id');
                $type=Yii::$app->request->get('type');
        $model=Team::findOne($teamId);
        if($model->userId==Yii::$app->user->id)
        {

           $member=TeamMembers::find()->where(['memberId'=>$id,'teamId'=>$teamId,'member_status'=>$type])->one();
        	$member->delete();
        }
        return $this->redirect(['team/'.$model->id]);
    }
      public function actionActivateInvite()
    {
     $key=Yii::$app->request->get('key');
        $invite=TeamInvites::find()->where(['invite_code'=>$key])->one();
        if($invite->id&&Yii::$app->user->id!=$invite->userId)
        {
              $members=new TeamMembers();
                $members->memberId=Yii::$app->user->id;
                $members->teamId= $invite->teamId;
        	     $members->member_status=$invite->invite_role;
        	      $members->save();
        	$invite->delete();
        	 Yii::$app->getSession()->setFlash('success', 'Вы успешно активировали приглашение в команду!');
        return $this->redirect(['activity/']);
     }
     elseif($invite->id&&Yii::$app->user->id==$invite->userId){
            throw new \yii\web\ForbiddenHttpException('Вы являетесь основателем данной группы и не можете добавить себя в команду');
           }
     else {
            throw new \yii\web\ForbiddenHttpException('Ошибка активации. Возможно ссылка устарела');
           }

    }
       private function SendInvite($model,$members)
    {
          Yii::$app->mailer->compose('invite-body',['model'=>$model,'members'=>$members])
                ->setTo($members->invite_email)
                ->setFrom(Yii::$app->user->identity->email)
                ->setSubject("Приглашение в команду ".$model->name)
                ->send();

            return true;

    }
}

frontend/views/team/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use  yii\helpers\Url;
use kartik\popover\PopoverX;
use kartik\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Мои команды';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="team-index" >
<div class="text-right" >
    <p>
                   <?php
 $form = ActiveForm::begin(['id' => 'create-tm','method'=>'post','action'=>''.Url::to(['team/create']).'']);
PopoverX::begin([
'type'=>'success',
    'header' => '<i class="fa fa-group "></i> Создать команду',
    'placement' => PopoverX::ALIGN_LEFT,
    'toggleButton' => ['label'=>'<i class="fa fa-group "></i> Создать команду', 'class'=>'btn btn-xs btn-danger'],

       'size'=>'md',
    'footer'=>Html::submitButton('Создать команду', ['class'=>'btn btn-sm btn-success'])
]);
echo "<b>Название команды</b><br>";
echo Html::textInput('name');

PopoverX::end();
ActiveForm::end();
?>
    </p>
</div>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
             	[
	 		'attribute' => 'name',
	 		'format'=>'html',
		       'value'=>function ($data) {
		        return Html::a($data->name,'team/'.$data->id);
		    },
      ],
            'created_at:date',
     	[
	 		'attribute' => 'numof',
	 		  'label'=>'Кол-во участников',
	 		'format'=>'raw',
		       'value'=>function ($data) {
		        return $data->Members_count;
		    },
      ],
     [
            'class' => '\kartik\grid\ActionColumn',
            'template' => '{view} {delete}',


        ],

   ]
  ]); ?>
</div>

frontend/views/team/view.php
<?php

use kartik\grid\GridView;
use yii\widgets\Pjax;
use kartik\icons\Icon;
Icon::map($this);
use kartik\helpers\Html;
use kartik\helpers\Enum;
use kartik\popover\PopoverX;
use kartik\widgets\ActiveForm;
use  yii\helpers\Url;
use kartik\editable\Editable;

/* @var $this yii\web\View */
/* @var $model common\models\Team */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Команды', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
$this->title = false;
$this->params['breadcrumbs']=false;
$team=$model;
?>
<div class="team-view">

    <h2><?php
         echo Editable::widget([
    'name'=>'name',
        'format' => Editable::FORMAT_BUTTON,
    'asPopover' => true,
    'value' => $model->name,
    'header' => 'Название команды',
    'size'=>'md',
        'resetButton'=>['icon'=>'Отменить','label'=>'Отменить'],
    'submitButton'=>['icon'=>'Применить','label'=>'Применить'],
    'options' => ['class'=>'form-control', 'placeholder'=>'Enter  name...']
]);?></h2>
      <div class="row">
            <div class="col-md-6">
        <div class="text-right">
        <?php
         $form = ActiveForm::begin(['action'=>'view?id='.$model->id,'fieldConfig'=>['showLabels'=>false]]);
PopoverX::begin([
    'header' => 'Добавить руководителя',
    'placement' => PopoverX::ALIGN_LEFT,
    'size' => 'lg',
    'footer' => Html::submitButton('Отправить', ['class'=>'btn btn-sm btn-primary']),
    'toggleButton' => ['label'=>'Добавить руководителя', 'class'=>'btn btn-success'],
]);
$members->invite_role=1;
?>

<b>Введите Email нового руководителя</b>
<br />

На указанный email будет отправлено приглашение стать частью команды. О подтверждении приглашения мы уведомим через email и отобразим в данном разделе
<? echo $form->field($members, 'invite_role')->hiddenInput()?>
<? echo $form->field($members, 'invite_email')->textInput(['placeholder'=>'Введите email...'])?>
<?php
PopoverX::end();
ActiveForm::end();
        ?>
        </div>
	&nbsp;
	<div class="box box-success box-solid">
            			<div class="box-header with-border">
              					<h3 class="box-title">Руководители</h3>

		              			<div class="box-tools pull-right">
		                			<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
		              			</div>
            			</div>

		            <div class="box-body" style="display: block;">

 <?= GridView::widget([
        'dataProvider' =>$leaderProvider,
           'pjax' => true,
           'bordered' => false,
            'layout' => '{items}',
            'showPageSummary' => false,
               // 'showCaption' => false,
         //  'showHeader'=>false,
    'striped' => false,
    'condensed' => false,
    'responsive' => true,
    'hover' => true,
    'floatHeader' => false,
         'columns' =>
         [
         'id',
         'username',
         'email',
        /*	[
    'attribute' => 'phone',
    'format' => 'html',
    'value' => function($data) { return $data->profile->phone; },
],
         */
 [
        'class' => '\kartik\grid\ActionColumn',
        'header'=>'Статус',
         'template' => '{my_button}',
         'buttons' => [
    'my_button' => function ($url, $model, $key)  use ($team) {
        return $model->id==Yii::$app->user->id?'<small class="label label-info">Основатель</small>':Html::a('Удалить', ['delete-member','teamId'=>$team->id,'type'=>1, 'id'=>$model->id],['class'=>'btn btn-danger']);
    },
]

    ]
],


    ]); ?>

		            </div>
        		  </div>
            </div>

        <div class="col-md-6">
        <div class="text-right">
                    <?php
         $form = ActiveForm::begin(['action'=>'view?id='.$model->id,'fieldConfig'=>['showLabels'=>false]]);
PopoverX::begin([
    'header' => 'Добавить менеджера',
    'placement' => PopoverX::ALIGN_LEFT,
    'size' => 'lg',
    'footer' => Html::submitButton('Отправить', ['class'=>'btn btn-sm btn-primary']),
    'toggleButton' => ['label'=>'Добавить менеджера', 'class'=>'btn btn-info'],
]);
$members->invite_role=2;
?>

<b>Введите Email нового менеджера</b>
<br />

На указанный email будет отправлено приглашение стать частью команды. О подтверждении приглашения мы уведомим через email и отобразим в данном разделе
<? echo $form->field($members, 'invite_role')->hiddenInput()?>
<? echo $form->field($members, 'invite_email')->textInput(['placeholder'=>'Введите email...'])?>
<?php
PopoverX::end();
ActiveForm::end();
        ?>
        </div>
&nbsp;
		<div class="box box-info box-solid">
            			<div class="box-header with-border">
              					<h3 class="box-title">Менеджеры</h3>

		              			<div class="box-tools pull-right">
		                			<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
		              			</div>
            			</div>

		            <div class="box-body" style="display: block;">

 <?= GridView::widget([
        'dataProvider' =>$managerProvider,
           'pjax' => true,
           'bordered' => false,
            'layout' => '{items}',
            'showPageSummary' => false,
               // 'showCaption' => false,
         //  'showHeader'=>false,
    'striped' => false,
    'condensed' => false,
    'responsive' => true,
    'hover' => true,
    'floatHeader' => false,
         'columns' =>
         [
        'id',
         'username',
         'email',
        /*	[
    'attribute' => 'phone',
    'format' => 'html',
    'value' => function($data) { return $data->profile->phone; },
],
         */
 [
        'class' => '\kartik\grid\ActionColumn',
         'header'=>'Статус',
         'template' => '{my_button}',
         'buttons' => [
    'my_button' => function ($url, $model, $key) {
        return $model->id==Yii::$app->user->id?'<small class="label label-info">Основатель</small>':Html::a('Удалить', ['delete-member', 'id'=>$model->id],['class'=>'btn btn-danger']);
    },
]

    ]
],


    ]); ?>

		            </div>
        		  </div>
            </div>

            </div>
</div>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<div class="row">
     <div class="col-md-12">
		<div class="box box-default box-solid">
            			<div class="box-header with-border">
              					<h3 class="box-title">Ожидают приглашения</h3>

		              			<div class="box-tools pull-right">
		                			<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
		              			</div>
            			</div>

		            <div class="box-body" style="display: block;">

 <?= GridView::widget([
        'dataProvider' =>$invitesProvider,
           'pjax' => true,
           'bordered' => false,
            'layout' => '{items}',
            'showPageSummary' => false,
               // 'showCaption' => false,
         //  'showHeader'=>false,
    'striped' => false,
    'condensed' => false,
    'responsive' => true,
    'hover' => true,
    'floatHeader' => false,
         'columns' =>
         [
        'id',

         'invite_email',

              	[
    'attribute' => 'invite_role',
    'format' => 'html',
    'value' => function($data) { return $data->invite_role==1?'Руководитель':'Менеджер'; },
],
             'created_at:date',
 [
        'class' => '\kartik\grid\ActionColumn',
         'template' => '{my_button}{delete}',
         'buttons' => [
    'my_button' => function ($url, $model, $key) {
        return '';
    },
],
      'urlCreator' => function ($action, $model, $key, $index) {
            if ($action == 'delete') {
             return Url::toRoute(['team/delete-invite', 'id' => $key]);
        }
      }

    ]
],


    ]); ?>

		            </div>
        		  </div>
            </div>

            </div>