common/models/Documents.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use  yii\helpers\Url;
 use frontend\models\LinksViews;

/**
 * This is the model class for table "{{%file_storage_item}}".
 *
 * @property integer $id
 * @property string $component
 * @property string $base_url
 * @property string $path
 * @property string $type
 * @property integer $size
 * @property string $name
 * @property string $upload_ip
 * @property integer $created_at
 */
class Documents extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%documents}}';
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),

            ]
        ];
    }
     public $docFile;
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['path','userId', 'filename','source_name'], 'required'],
            [['size','userId'], 'integer'],
            [['docFile'], 'file', 'skipOnEmpty' => true, 'extensions' => 'ppt, pptx, pdf, xls, xlsx, doc, docx, pps, ppsx, jpg, gif, png','checkExtensionByMimeType'=>false,'maxSize' => 1024 * 1024 * 5],
            [['component', 'name','original', 'source_name'], 'string', 'max' => 255],
            [['path', 'base_url', 'filename'], 'string', 'max' => 1024],
            [['upload_ip'], 'string', 'max' => 15]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('common', 'ID'),
            'userId'=>Yii::t('common', 'User'),
            'filename' => Yii::t('common', 'FileName'),
            'source_name' => Yii::t('common', 'SourceName'),
            'component' => Yii::t('common', 'Component'),
            'base_url' => Yii::t('common', 'Base Url'),
            'path' => Yii::t('common', 'Path'),
            'type' => Yii::t('common', 'Type'),
            'size' => Yii::t('common', 'Size'),
            'name' => Yii::t('common', 'Name'),
            'original' => Yii::t('common', 'Original'),
            'isDeleted' => Yii::t('common', 'isDeleted'),
            'noParsed' => Yii::t('common', 'noParsed'),
            'upload_ip' => Yii::t('common', 'Upload Ip'),
            'created_at' => Yii::t('common', 'Created At')
        ];
    }
		public static function find()
		{
		    return new DocumentsQuery(get_called_class());
		}
      public function getVisits()
    {
          return $this->hasMany(LinksViews::className(), ['linkId' => 'id'])
           ->viaTable('links', ['docId' => 'id'])
          ->count();
    }
        public function getUser()
    {
          return $this->hasOne(User::className(), ['id' => 'userId']);
    }
        public function getPages()
    {
          return $this->hasMany(DocumentsPages::className(), ['docId' => 'id']);
    }
        public function getPreview()
    {
          return $this->dir.($this->noParsed==1?basename($this->source_name):$this->pages[0]->filename);
    }
        public function getThumb()
    {
          return $this->dir.'thumbs/'.($this->noParsed==1?basename($this->source_name):$this->pages[0]->filename);
    }

            public function getDir()
    {
          return Yii::$app->keyStorage->get('system.uploadDir').'/'.$this->repository.'/';
    }
            public function getFulldoc()
    {
          return \Yii::getAlias('@web').'/'.$this->dir.$this->filename;
    }
        public function getLinks()
    {
          return $this->hasMany(Links::className(), ['docId' => 'id']);
    }
        public function getTimeviews_sum()
    {
          //return LinksViews::find()->joinWith('link')->where(['docId'=>$this->id])->sum();
    }
         public static function Doc_count($uid,$today=0,$d1=0,$d2=0)
   {
     if($today){$m2=0;$m1=mktime(0,0,0,date('m'),date('d'),date('Y'));}
     $query=Documents::find()->where(['userId'=>$uid]);
     if($d1)$query->andwhere('created_at >=\''.(int)$d1.'\'');
     if($d2)$query->andwhere('created_at <=\''.(int)$d2.'\'');
     return $query->count();
    }
}

frontend/controllers/DocumentsController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Documents;
use common\models\search\DocumentsSearch;
use common\models\DocumentsPages;
use common\models\Links;
use common\models\Team;
use \common\models\DocumentsToTeam;
use frontend\models\Presentations;
use frontend\models\LinksViews;
use frontend\models\LinksViewsPages;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
 use yii\data\ActiveDataProvider;
 use  yii\helpers\Url;
use yii\helpers\Json;

class DocumentsController extends Controller
{
    public function behaviors() {
    return [
        'access' => [
            'class' =>  \yii\filters\AccessControl::className(),
            'rules' => [
                [
                    'allow' => true,
                    'roles' => ['@'],
                ],
            ],
        ],
    ];
}


    /**
     * Lists all Documents models.
     * @return mixed
     */
    public function actionIndex()
    {

        $totalSize = Documents::find()->sum('size') ?: 0;
            $dataProvider = new ActiveDataProvider([
              'query' => Documents::find()
              ->active()
              ->andwhere(['userId'=>Yii::$app->user->id])
              ->orderBy('id desc'),
                         'pagination' => [
        'pageSize' => 10,
    ],
        ]);

	if (Yii::$app->request->post()) {
         $newId=$this->FileUpload();
         if($newId)
         {
         	    Yii::$app->getSession()->setFlash('success', 'Файл закачан!');
			     return $this->redirect(['documents/']);
		 }
		 else
		 {
		 	    Yii::$app->getSession()->setFlash('warning', 'Ошибка, неверный формат файла!');
		 	    return $this->redirect(['documents/']);
		 }
    }
        return $this->render('index', [
            //'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            // 'totalSize' => $totalSize
        ]);
    }

    /**
     * Displays a single Documents model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model=$this->findModel($id);
        if(Yii::$app->request->post('hasEditable')&&$model->userId==Yii::$app->user->id)
        {
        	$model->name=Yii::$app->request->post('file_name');
        	$model->save();
        	 $out = Json::encode(['output'=>'', 'message'=>'']);
        	 echo $out;
        	 return;
        }
              $viewsProvider = new ActiveDataProvider([
              'query' => LinksViews::find()->joinWith('link')
              ->where(['links.docId'=>$model->id,'userId'=>Yii::$app->user->id])
             // ->andwhere(['is','letterId',null])
              ->orderBy('id desc'),
                          'pagination' => ['pageSize' => 10],
					        ]);

        return $this->render('view', [
            'model' => $model,
        'viewsProvider'=>$viewsProvider
     ]);
    }
   public function actionFileUploadSend()
    {

	if (Yii::$app->request->post()) {
         $newId= $this->FileUpload();
         if($newId)
         {
         	$result=['success'=>1,'docId'=>$newId];
              return Json::encode($result);
         }
         else
         {
         	         	$result=['success'=>0];
              return Json::encode($result);
         }
    }

    }
    private function FileUpload()
    {

           $model=new Documents;
			 $doc =UploadedFile::getInstanceByName('doc');
			 $model->docFile=$doc;
			   $model->name = $doc->name;
			   $isPDF=$doc->type=='application/pdf'?1:0;
			    $ext = end((explode(".", $doc->name)));
			    $uploadDir=Yii::$app->keyStorage->get('system.uploadDir');
			    $doc_r = Yii::$app->user->id.'_'.Yii::$app->security->generateRandomString(7);
			    $doc_n = Yii::$app->security->generateRandomString(7);
			    $path = $uploadDir . '/' . $doc_r . '/' . $doc_n.".{$ext}";
                $pdf=$isPDF==1?$path:$uploadDir . '/' . $doc_r. '/'.$doc_n.'.pdf';
                $pdf_dir=$uploadDir . '/' . $doc_r . '/';
                $emptyImgFile=$uploadDir . '/' . $doc_r. '/'.$doc_n.'.png';


			    $model->name = $doc->name;
                $model->userId = Yii::$app->user->id;
				$model->upload_ip = Yii::$app->getRequest()->getUserIP();
                $model->mimeType = $doc->type;
			    $model->size = $doc->size;
                $model->repository = $doc_r;
                $model->name = $doc->name;
                $model->original = $doc->name;
                $model->source_name = $doc_n;
                $model->filename = basename($pdf);
                $model->path = $path;


//	 print_r($model->getErrors());


			 if ($model->validate()) {


			    \yii\helpers\BaseFileHelper::createDirectory($uploadDir . '/' . $doc_r);
			    \yii\helpers\BaseFileHelper::createDirectory($uploadDir . '/' . $doc_r . '/thumbs');
			    $model->docFile->saveAs($path);
			    //$doc->saveAs($pdf);
                if($isPDF!==1)
                {
					    if(!in_array(strtolower($ext),array('xls','xlsx')))
					    {
							    $command=Yii::$app->params['pdfConverter'];
							    $command=str_replace('{filename-in}',$path,$command);
							    $command=str_replace('{filename-out}',$pdf,$command);
							    $response=exec($command,$out,$res);

							 //   echo $command.$res;
							 //   echo "--".$response;
							  //  exit;
			             }
			    if(strlen($response)>0||!file_exists($pdf))$model->noParsed=1;
			    }

			    if($model->noParsed==1)
			    {
			    	   $image = new \Imagick();
						$image->newImage(300, 400, new \ImagickPixel('#34AB4B'));
						$image->setImageFormat('png');

                    $draw = new \ImagickDraw();
					$draw->setFillColor('black');
					//$draw->setFont('Arial');
					$draw->setFontSize( 30 );
					$image->annotateImage($draw, 100, 100, 0, 'Excel ');
					    $image->writeimage(\Yii::getAlias('@webroot').'/'.$emptyImgFile);
					  $save_to_th=Yii::getAlias('@webroot').'/'.$uploadDir.'/'.$model->repository.'/thumbs/'.basename($emptyImgFile);
					    exec(Yii::$app->params['imagickPath'].' -resize '.Yii::$app->keyStorage->get('common.thumbs_width').' '.$emptyImgFile.' '.$save_to_th);
                     $model->source_name = $emptyImgFile;
                $model->filename = basename($path);
			    }
			    $model->docFile=null;
			    $model->save(false);

                if($model->noParsed!==1)
			    {
			       $im = new \Imagick();
				   $im->pingImage(Yii::getAlias('@webroot').'/'.$pdf);
				   $pages_num=$im->getNumberImages();
						   for($z=0;$z<$pages_num;$z++)
						   {
						   	    $page_img=Yii::$app->security->generateRandomString(10).".jpg";
						   	    $save_to=Yii::getAlias('@webroot').'/'.$uploadDir.'/'.$model->repository.'/'.$page_img;
						   	    $save_to_th=Yii::getAlias('@webroot').'/'.$uploadDir.'/'.$model->repository.'/thumbs/'.$page_img;


								exec(Yii::$app->params['imagickPath'].' -background white '.Yii::getAlias('@webroot').'/'.$pdf.'['.$z.']  -quality 95 '.$save_to);
		//						exec(Yii::$app->params['imagickPath'].' -resample 72 -density 175 -background white -alpha remove  '.Yii::getAlias('@webroot').'/'.$pdf.'['.$z.']  -quality 95 '.$save_to);
								exec(Yii::$app->params['imagickPath'].' -resize '.Yii::$app->keyStorage->get('common.thumbs_width').' '.$save_to.' '.$save_to_th);
								$page=new DocumentsPages;
								$page->docId=$model->id;
								$page->filename=$page_img;
								$page->pageNum=($z+1);
		                        if ($page->validate()) {
		                         $page->save();
		                        }
		                   }

				   }
			return $model->id;
             }
             else {
               return false;
             }
    }

    /**
     * Deletes an existing Documents model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model=$this->findModel($id);

        if($model->userId==Yii::$app->user->id)
        {

        	$model->isDeleted=1;
        	$model->save();
         }

        return $this->redirect(['documents/']);
    }
     public function actionCorrectPageNum()
    {
     $docs=Documents::find()->all();
     foreach($docs as $doc)
     {
       $pages=DocumentsPages::find()->where(['docId'=>$doc->id])->orderby('id')->all();
       $cnt=1;
            foreach($pages as $page)
		    {
		        echo $page->id."--$cnt<br>";
		    	$page->pageNum=$cnt;
		    	$page->save();
		    	print_r($page->getErrors());
		    	LinksViewsPages::updateAll(['pageNum'=>$cnt], ['pageId'=>$page->id]);
		    	$cnt++;
		    }
      }
    }
     public function actionDocList()
    {
        $data=Documents::find()->active()
              ->andwhere(['userId'=>Yii::$app->user->id])
              ->andwhere(['!=','noParsed',1])
              ->orderBy('id desc')->limit(150)->all();

        return $this->renderPartial('ajax/_doc_list', [
            'data'=>$data
        ]);
    }
     public function actionPagesList()
    {
      $id=Yii::$app->request->post('id');
       $data=Documents::find()->active()
              ->andwhere(['id'=>$id])
              ->andwhere(['userId'=>Yii::$app->user->id])
              ->orderBy('id desc')->limit(150)->one();

        return $this->renderPartial('ajax/_pages_list', [
            'data'=>$data
        ]);
    }
     public function actionBlockLink()
    {
        $model=Links::findOne(Yii::$app->request->post('id'));
        $status=Yii::$app->request->post('status');
        if($model->userId==Yii::$app->user->id)
        {

        	$model->isBlocked=$status=='false'?1:0;
        	echo $model->isBlocked;
        	$model->save();
         }

    }
    /**
     * Finds the Documents model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Documents the loaded model

frontend/views/documents/ajax/_charts.php
<?php

use yii\helpers\Url;
use tugmaks\GoogleMaps\Map;
use common\models\Links;
use common\models\Letters;
use frontend\models\LinksViews;
use kartik\helpers\Enum;
use kartik\helpers\Html;
$data=LinksViews::find()->joinwith('link')->where(['links.docId'=>$model->id])->all();
$locs=[];
    foreach($data as $v)if($v->client_country)$locs[]=['position'=>$v->client_country.' '.$v->client_city];

$stat[]=['Число визитов',5];
$stat[]=['Общее время просмотра',7];
$stat[]=['Количество скачиваний',4];
$stat[]=['Всего писем',5];
 ?>
 <div class="row">
 <div class="col-md-6">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Наиболее просматриваемая страница</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body no-padding">
              <table class="table table-condensed">
                <tbody>
                <tr>
                  <td><div class="thumbnail thumbnail-blue docthumbnail"><?=Html::img(Url::to(['/']).$model->preview, ['width'=>'60'])?></div></td>
                  <td></td>
                </tr>

              </tbody></table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
<div class="col-md-6">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Общая статистика по документу</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body no-padding">
              <table class="table table-condensed">
                <tbody>
                <tr>
                  <td>1.</td>
                  <td>Число визитов</td>
                  <td><span class="badge bg-red"><?=Links::find()->joinWith('views',true,'RIGHT JOIN')->where(['links.docId' => $model->id])->count()?></span></td>
                </tr>
                <tr>
                  <td>2.</td>
                  <td>Общее время просмотра</td>
                  <td><span class="badge bg-yellow"><?= gmdate("H:i:s", (int)Links::find()->joinWith('views',true,'RIGHT JOIN')->where(['links.docId' => $model->id])->sum('views.ended_at-views.created_at'))?></span></td>
                </tr>
                <tr>
                  <td>3.</td>
                  <td>Всего писем</td>
                  <td><span class="badge bg-light-blue"><?=Letters::find()->joinWith('links',true,'RIGHT JOIN')->where(['docId' => $model->id])->count()?></span></td>
                </tr>
                <tr>
                  <td>4.</td>
                  <td>Количество скачиваний</td>
                  <td><span class="badge bg-green"><?=Links::find()->joinWith('views',true,'RIGHT JOIN')->where(['links.docId' => $model->id,'downloads'=>1])->count()?></span></td>
                </tr>
              </tbody></table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
 </div>
 <div class="row">
            <div class="col-md-12">

</div>
</div>

frontend/views/documents/ajax/_doc_list.php
<?php
use kartik\helpers\Html;
use  yii\helpers\Url;
use kartik\grid\GridView;
use kartik\icons\Icon;
Icon::map($this);
use kartik\widgets\SwitchInput;


?>
             <div class="row link-block">
                   <div class="col-md-12">
                      <?php foreach($data as $doc):?>
                          <div style="margin:8px"><?php echo Icon::show('chevron-circle-down', ['class'=>'fa-1x'])." &nbsp;".Html::a($doc->name,'#',['class'=>'','onClick'=>'SelectDoc('.$doc->id.')']);?></div>
                      <?php endforeach?>
                   </div>

             </div>

frontend/views/documents/ajax/_doc_team.php
<?php
use kartik\helpers\Html;
use  yii\helpers\Url;
use yii\helpers\ArrayHelper;
use kartik\icons\Icon;
Icon::map($this);
use kartik\form\ActiveForm;
use common\models\Team;
use common\models\DocumentsToTeam;
$teams=yii\helpers\ArrayHelper::map(Team::find()->joinWith('members',true,'RIGHT JOIN')->where(['memberId' => Yii::$app->user->id])->asArray()->all(),'id','name');
$teams_selected=ArrayHelper::map(DocumentsToTeam::find()->where(['docId' => $doc->id])->asArray()->all(),'','teamId');

?>
             <div class="row link-block">
                   <div class="col-md-12">
                   <?php if(count($teams)==0):?>
                   <p>Вы не приписаны ни к одной команде</p>
                     <?php else:?>
  <?php
  $form = ActiveForm::begin([
    'id' => 'docTeamForm',
    'type' => ActiveForm::TYPE_VERTICAL
]);
?>
  <?php
  $model->docId=$doc->id;
echo $form->field($model, 'docId')->hiddenInput()->label(false); ?>
<?php
echo $form->field($model, 'teamList')->checkboxList($teams,
    ['item' =>
        function($index, $label, $name, $checked, $value) use ($teams_selected) {
            $checked=ArrayHelper::IsIn($value,$teams_selected)?'checked=checked':'';
             return "<label class='ckbox ckbox-primary col-md-4'><input type='checkbox' {$checked} name='{$name}' value='{$value}' tabindex='3'>&nbsp;&nbsp;{$label}</label>";

        }
    ]); ?>
     <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <?= Html::submitButton('Обновить', ['id'=>'tmBtn','class' => 'btn btn-primary']) ?>
        </div>
    </div>
<?
ActiveForm::end();
?>
 <?php endif;?>
     </div>

             </div>

frontend/views/documents/ajax/_links_form.php
<?php
use yii\helpers\Html;
use  yii\helpers\Url;

use yii\helpers\ArrayHelper;
use kartik\widgets\ActiveForm;
use kartik\builder\Form;
use kartik\builder\FormGrid;

use kartik\icons\Icon;
Icon::map($this);
$this->title = 'Создать ссылку';
$this->params['breadcrumbs'][] = $this->title;



?>
<div class="row email-form">
       <div class="col-md-10 col-md-offset-1">
              <div class="panel panel-default">
                                                <div class="panel-body">
<?php
  $form = ActiveForm::begin(['id'=>'createLinkForm','type'=>ActiveForm::TYPE_HORIZONTAL]);
echo FormGrid::widget([
    'model'=>$model,
    'form'=>$form,
    'autoGenerateColumns'=>true,
    'rows'=>[
        [
      'contentBefore'=>'<legend class="text-info"><small>Карточка клиента</small></legend>',
            'attributes' => [
                                'client_name'=>['type'=>Form::INPUT_TEXT,'options'=>[],
                                'hint'=>'укажите любые данные о клиенте, которые получите в уведомлении'
                                ],

            ],
        ],
           [
            'attributes' => [
                                'docId'=>['type'=>Form::INPUT_HIDDEN,'label'=>'',],

            ],
        ],
            [
            'attributes' => [
                                'client_company'=>['type'=>Form::INPUT_TEXT,'options'=>[],
                                ],
            ],
        ],
        [
            'attributes' => [
                                'client_phone'=>['type'=>Form::INPUT_TEXT,'options'=>[],
                                'hint'=>'укажите номер клиента, чтобы иметь возможность быстро перезвонить ему после получения уведомления'
                                ],
            ],
        ],
        [
      'contentBefore'=>'<legend class="text-info"><small>Расширенные опции</small></legend>',
      'attributes' => [
            'denyDownloading'=>[       'type'=>Form::INPUT_WIDGET,
            'widgetClass'=>'kartik\checkbox\CheckboxX',
            'label'=>'',

			             'options' => [
                                   'autoLabel'=>true,
                                    'pluginOptions'=>['threeState'=>false],
			                       'labelSettings' => ['position' => kartik\checkbox\CheckboxX::LABEL_RIGHT]
						 ]
	           ],
            ],
        ],
        [
      'attributes' => [
            'isProtect'=>[       'type'=>Form::INPUT_WIDGET,
            'widgetClass'=>'kartik\checkbox\CheckboxX',
            'label'=>'',

			             'options' => [
                                   'autoLabel'=>true,
                                    'pluginOptions'=>['threeState'=>false],
			                       'labelSettings' => ['position' => kartik\checkbox\CheckboxX::LABEL_RIGHT],
			                        'pluginEvents' => [
			                         'change'=>'function(e) {var el = $(e.target);
			                         if(el.val()==1)$("#protect_code_el").removeClass("hidden");
			                         else $("#protect_code_el").addClass("hidden");  }',
			                        ],
						 ]
	           ],
            ],
        ],
         [
      'contentBefore'=>'<div id="protect_code_el" class="hidden">',
      'contentAfter'=>'</div>',
            'attributes' => [
                                'protect_code'=>['type'=>Form::INPUT_TEXT,'options'=>[]],

            ],
        ],
        [
      'attributes' => [
            'isExpire'=>[       'type'=>Form::INPUT_WIDGET,
            'widgetClass'=>'kartik\checkbox\CheckboxX',
            'label'=>'',

			             'options' => [
                                   'autoLabel'=>true,
                                    'pluginOptions'=>['threeState'=>false],
			                       'labelSettings' => ['position' => kartik\checkbox\CheckboxX::LABEL_RIGHT],
			                        'pluginEvents' => [
			                         'change'=>'function(e) {var el = $(e.target);
			                         if(el.val()==1)$("#expired_date_el").removeClass("hidden");
			                         else $("#expired_date_el").addClass("hidden");  }',
			                        ],
						 ]
	           ],
            ],
        ],
        [
         'attributes' => [
                'expired_date'=>['type'=>Form::INPUT_WIDGET,
          'label'=>'',
                  'widgetClass'=>'\kartik\widgets\DateTimePicker',
                     'hint'=>'Время московское',
                'options'=>[
                   'options'=>['placeholder'=>'Дата истечения ..', 'pluginOptions' => ['autoclose' => true]],
                ]],
            ],
        ],

                [
            'attributes'=>[
                'actions'=>[    // embed raw HTML content
                    'type'=>Form::INPUT_RAW,
                    'value'=>  '<div style="text-align: right; margin-top: 20px">' .
                           Html::submitButton('Сохранить', ['class'=>'btn btn-primary']) .
                        '</div>'
                ],
            ],
        ],
    ]
]);
ActiveForm::end();

?>
                </div>
                  </div>
    </div>
</div>
<div class="clear"></div>

frontend/views/documents/ajax/_pages_list.php
<?php
use kartik\helpers\Html;
use  yii\helpers\Url;
use kartik\grid\GridView;
use kartik\icons\Icon;
Icon::map($this);
use kartik\widgets\SwitchInput;


?>
             <div class="row link-block">
             <p>&nbsp;</p>
             <div style="color:#cacaca"><b><?=$data->name?><u></u></b></div>
             &nbsp;
                      <?php foreach($data->pages as $page):
                      $cnt++;
                      ?>
                          <div class="page-item" data-pageid="<?=$page->id?>" onClick="changePage('<?=$page->id?>','')" style="margin:10px;width:130px;color:#FFF">Страница № <?php echo $cnt;?>
                          <div class="thumbnail thumbnail-blue"><?php echo Html::a(Html::img(Url::to(['/'],true).$data->dir.'/thumbs/'.$page->filename, ['id'=>'page'.$page->id,
                          'width'=>'116','data-imgsrc'=>Url::to(['/'],true).$data->dir.'/'.$page->filename]),'#');?></div>
                          </div>
                      <?php endforeach?>
             </div>

frontend/views/documents/ajax/_view_stats.php
<?php
use kartik\helpers\Html;
use  yii\helpers\Url;
use frontend\models\LinksViewsPages;
foreach($model->link->doc->pages as $page)
{
       $num++;
       // echo $page->docId;
         //     echo $page->pageNum;
           // $query =LinksViewsPages::find()->where(['pageNum'=>$page->pageNum,'client_session'=>$model->client_session]);
    //echo $query->createCommand()->getRawSql();
       $stat=LinksViewsPages::find()->where(['pageNum'=>$num,'client_session'=>$model->client_session])->sum('ended_at-created_at');
       $stats[]=['category'=>'Страница '.$num,'column-1'=>(int)$stat];
       $pages[]='№'.$num;
}

?>
<div class="row" style="border:0px solid" >
  <div class="col-md-12 text-left" style="background:#FFF;border:1px dashed #86CCF7;padding:10px">
   <div class="col-md-6">
     Дата визита: <?=date('Y-m-d h:i',$model->created_at);?><br>
     Общее время просмотра: <?=$model->interval;?> (мин:сек)<br>
     IP: <?=$model->client_ip;?><br>
     Скачивание: <?=$model->downloads;?><br>
     Печать: <?=$model->print;?><br>
  </div>
   <div class="col-md-6">
     Город: <?=$model->client_city;?><br>
     Страна: <?=$model->client_country;?><br>
          Платформа: <?=$model->client_os;?><br>
               Броузер: <?=$model->client_browser;?><br>
                    Тип устройства: <?=$model->device;?>
  </div>
  </div>
  </div>
<div class="row">
  <div class="col-md-12">
  <?php if($model->link->doc->noParsed==1):?>
            <?php
echo Html::jumbotron([
    'heading' => '',
    'body' => 'Структура документа не позволяет разложить его по слайдам,<br /> и отобразить постраничную статистику<br>Документ был скачан напрямую',

]);
?>
 <?php else:?>
	<!-- amCharts javascript code -->
		<script type="text/javascript">
		 var chart = AmCharts.makeChart("chartdiv",
				{
					"type": "serial",
					"categoryField": "category",
					"startDuration": 1,
					"categoryAxis": {
						"gridPosition": "start",
						"dateFormats":[{period:'ss',format:'JJ:NN:SS'}]

					},
					"chartCursor": {
						"enabled": true
					},
					"chartScrollbar": {
						"enabled": true
					},
					"trendLines": [],
					"graphs": [
						{
							"fillAlphas": 1,
							"id": "AmGraph-1",
							"title": "graph 1",
							"type": "column",
							"valueField": "column-1"
						}
					],
					"guides": [],
					"valueAxes": [
						{
							"id": "ValueAxis-1",
							"title": "Время, сек"
						}
					],
					"allLabels": [],
					"balloon": {},
					"titles": [
						{
							"id": "Title-1",
							"size": 15,
							"text": "Статистика по страницам"
						}
					],
					"dataProvider": <?=json_encode($stats)?>
				}
			);

		</script>

		<div id="chartdiv" style="width: 100%; height: 400px; background-color: #FFFFFF;" ></div>
            <?php endif;?>
  </div>

</div>